<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>

<h1>Preview Units to be Added</h1>
<h4>Serial Number will be autogenerated if an identical one is found</h4>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID Warehouse</th>
            <th>Serial Number</th>
            <th>Comment</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($unitData as $unit): ?>
            <tr>
                <td><?= Html::encode($unit['id_wh']) ?></td>
                <td><?= Html::encode($unit['serial_number']) ?></td>
                <td><?= Html::encode($unit['comment']) ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?= Html::beginForm(['bulk-add-preview'], 'post') ?>
    <?= Html::submitButton('Confirm Save', ['class' => 'btn btn-success']) ?>
<?= Html::endForm() ?>
